### PR TITLE
responsive

### PR DESCRIPTION
**Pull request by BenediktSeidl**
On Thu, 30 Jun 2016 11:01:07 -0700 Trevor Perrin wrote:

> I'm terrible at websites, if anyone has web
> skills and wants to make suggestions for the site, it's here:
> https://github.com/noiseprotocol/noiseprotocol.github.io

Not sure if you looked for a complete overhaul, I've just tried to make the current design responsive and cleaned up the code. Probably still not perfect, but should improve the current state.

### CODE REVIEW

**Comment by trevp** [comment]
Thanks!, it definitely needs a cleanup, I'll try to get to this next week.

**Comment by trevp** [comment]
Thanks Benedikt, I finally merged this, it's visible on:

https://noiseprotocol.org/dev

I'm wondering if the white text for "Noise Protocol Framework" should be bigger, as before, and maybe the blue for "Read Specification" should be deeper, so it stands out more?  On mobile, the "Rust" and "C" buttons end up almost touching, I wonder if more space could be added?

**Comment by BenediktSeidl** [comment]
~~Oh! I think I've made a mistake. Is there a way to change this pull request to dev, or should I open a new one?~~ _found the edit button_

Anyway, I've added some shadows and a image:
- "Noise Protocol Framework" should be more prominent (black shadow)
- The "Read Specification" button got an icon and a white shadow
- Buttons "Rust" and "C" should no longer touch

If you want i can still change the color of the button or change the font size.

**Comment by trevp** [comment]
Thanks, applied to dev site - I like the mobile version, but I'm not sold on the changes to the initial banner (shadows, smaller text, darker image, different color button).  I would just keep them the same for now (except perhaps centering the button, that seems fine), and we can consider different cosmetics later.

**Pull request merged**
